### ISSUE TITLE
Spring Security Licensing information

### ISSUE THREAD

**Issue by Vidmaster** [Vidmaster/cybr8420-group4#7]
Add a section to the project proposal to discuss License, procedures for making contributions, and contributor agreements for Spring Security

**Comment by btomey** [comment]
Contributor Code of Conduct
⦁	Unacceptable behavior will cause you to be temporarily or permanently banned
⦁	Do not use sexualized language or imagery
⦁	No Trolling or derogatory comments
⦁	No personal, public or private attacks
⦁	Do not publish private information with out owner permission
⦁	No unethical or unprofessional conduct
Project maintainers have the responsibility to remove code, commits, wiki edits and anything thing else that violate these Contributor Code of Conduct. The Code of Conduct applies to public and private spaces within the project.
Search GitHub issues before creating an issue, to make sure the issue is not already reported.
Discuss non-trivial contribution with committers before submitting a pull request. Non trivial contribution are fixing typos or minor bugs.
Fill out and submit the Contributor License Agreement. https://cla.pivotal.io/sign/spring
Create your branch from the master to be submitted as a pull request.
Do not use long branch names pick short branch names. They need to be lower-case and dash delimited names i.e. pro-fixed.
Follow white space and formatting convention.
⦁	This is outline in the Mind the white space section of CONTRIBUTING.adoc
Update spring-securityx.y.rnc for schema changes not spring-securityx.y.xsd
Squash commits, examples are out lined here https://book.git-scm.com/4_interactive_rebasing.html
Use real name in git commits.

License  is Aache License 2.0, spring-projects/spring-security can be used for Commercial use. You can Modify, Distribute. You can use in Patent use and Private use. You can not Trademark use, there is no Liability or warranty.

**Comment by btomey** [comment]
Second try:

Contributor Code of Conduct
You will be banned if you 
⦁	Talk about or share sexual explicit material
⦁	If you troll
⦁	 Cyber bulling
⦁	Plagiarize
⦁	Unethical or Illegal behavior
Project maintainers will  remove code, commits, or wiki edits, if these rules are violated. The Code of Conduct applies to the project both public and private space.
Before submitting  an issue Search GitHub to see if it is already reported.
Discuss contribution with committers before submitting a pull request, if it is a bug fix or a typo correction that can be fixed with out bothering the committers.
Fill out and submit the Contributor License Agreement located at https://cla.pivotal.io/sign/spring before you contribute.
Create your branch from the master to be submitted as a pull request.
Do not use long branch names pick short branch names. The example is the proffered branch name type. Example: pro-fixed.
Follow whitespace and formatting convention. The formatting convention is in the Mind the whitespace section of CONTRIBUTING.adoc
Update spring-securityx.y.rnc for schema changes do not change spring-securityx.y.xsd
Squash commits, examples are located here https://book.git-scm.com/4_interactive_rebasing.html
Use real name in your git commits.

**Comment by Vidmaster** [comment]
Looks good, go ahead and add it to the main document and close this out!
